name: Test Push Directory to Branch with PR

on:
  push:
    branches:
      - main  # 触发的分支

# ref https://docs.github.com/zh/actions/learn-github-actions/variables
env:
  dist_path: ".github"
  dist_branch: "main_-_dist_-_test" # 不能包含 / 等字符
  # 有个小缺陷需要解决，fokr端（下游）创建分支时必须同名，否则只有创建时是复制的制定分支，后续目标会被强制改为上游默认分支
  # 试试工作流 git branch —set-upstream-to

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保可以获取所有历史记录，以便合并
          token: ${{ secrets.MY_GH_TOKEN_W }} # 使用具有完全写入权限的 TOKEN（必须包含 workflows ）

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Check out dist_branch or create it if it doesn't exist
        run: |
          git checkout ${{ env.dist_branch }} || git checkout -b ${{ env.dist_branch }}

      - name: Merge changes from main into dist_branch
        run: |
          git checkout main
          cp -r ${{ env.dist_path }} /tmp/
          ls -la /tmp/${{ env.dist_path }}
          git checkout ${{ env.dist_branch }}
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          # 移动所有非隐藏文件和目录
          mv /tmp/${{ env.dist_path }}/* .
          # 移动所有隐藏文件和目录，但排除 . 和 ..
          shopt -s dotglob nullglob
          mv /tmp/${{ env.dist_path }}/.[!.]* .
          shopt -u dotglob nullglob
          # shopt -s dotglob 命令将开启shell选项，使得通配符 * 包含以点开头的文件和目录。
          # nullglob 选项确保当没有匹配的文件时，通配符不展开为自身。
          # 之后，我们通过 shopt -u dotglob nullglob 命令关闭这些选项，以恢复默认行为。
          ls -la
          git add .
          git commit -m "[bot][skip actions] Merge changes into ${{ env.dist_branch }}" || echo "No changes to commit"

      - name: Push changes
        id: push_changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ env.dist_branch }}
          force: true
          # force_with_lease: true # 仅在远程分支自上次检出以来没有其他提交的情况下成功
        env:
          github_token: ${{ secrets.MY_GH_TOKEN_W }} # 使用具有完全写入权限的 TOKEN（必须包含 workflows ）

